### ISSUE TITLE
Mod Breaks the Statistics Page

### ISSUE THREAD

**Issue by Darkosto** [MinecraftModDevelopmentMods/spooky-biomes#5]
Hello!

I've recently discovered that Spooky Biomes stops the statistics page from showing up. The following NPE appears in the log when attempting to open stats: 

https://pastebin.com/E2xpEWge

I went ahead and created an instance with only Spooky Biomes and Proxy's Lib mods to confirm it's Spooky Biomes (stats page shows up when using only the lib mod). 

MC: 1.12.2
Forge: 2847
Spooky Biomes: 1.1.1
Proxy's Lib: 1.1.0

Thank you!
Darkosto

**Comment by ProxyNeko** [comment]
Odd I don’t remember doing anything with stats or things like that but I can try and look into the jar when I have a moment (busy irl for a few weeks sadly) but no promises as I don’t have the code for that version anymore and I’m in the middle of a very big rewrite.

I may be able to pull the older code out of the jar though and see if I can fix the problem but that feels like a long shot.

Thanks for the report though :)

**Comment by ProxyNeko** [comment]
So far I've not had the issue with the stuff I've had in dev for ages so if it was just clicking on the stats menu or General, Blocks, Items and Mobs then it's fixed so I just need to finish up the other things I was adding in. (I think it was the way I registered mobs in the older version but that had been changed since thankfully)

Quick warning though that the textures since the last release have changed for the existing things and the registry names have changed so blocks may vanish in the world (Will package up the old textures as a resource pack because I know some people like those ones and link it on the mods curse page)

**Comment by ProxyNeko** [comment]
I’ve released a few updates and fixes all in one (in 1.2.0.8 I think but the last number does not matter so much) this hopefully fixes the issue you brought up coz I’ve not been able to replicate it :)

Will try release an update again later (if I get a moment of time tonight) to finish up a few cosmetic things like bloodwood trees spawning dirt under them and seeping logs not being animated but any more troubles just list them here or DM me on Discord an I’ll be happy to try fix em for you :)
